Week 4 - Test services with not global Context
Tynukua/scala-course-2022-spring-D-Volodymyr pull request #4
Opened 2022-06-18 09:27 UTC by Tynukua

2022-06-21 10:35 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week4/homework/services.scala
> +// import concurrent.ExecutionContext.Implicits.global
Remove it please.

2022-06-21 10:35 UTC, IgorWolkov commented on src/test/scala/karazin/scala/users/group/week4/homework/ProgramSuite.scala
> +      views.map(v => print(v))(using executor = context())
No `print(v)`! Remove it please.

2022-06-21 10:36 UTC, IgorWolkov requested changes
Some minor comments.

2022-06-27 10:29 UTC, IgorWolkov commented on src/test/scala/karazin/scala/users/group/week4/homework/ProgramSuite.scala
> +      val views = getPostsViews()(using context())
Looks like this test checks nothing.

2022-06-27 10:29 UTC, IgorWolkov commented on src/test/scala/karazin/scala/users/group/week4/homework/ServicesSuite.scala
> +      val profile = getUserProfile(using context())
Looks like this test checks nothing.

2022-06-27 10:29 UTC, IgorWolkov requested changes
The tests should be improved.

2022-06-27 10:37 UTC, Tynukua commented on src/test/scala/karazin/scala/users/group/week4/homework/ProgramSuite.scala
> +      val views = getPostsViews()(using context())
it tests context creating and using 

check some data is impossible cuz it's random
checking the type of ret value is also meanless

2022-06-28 21:45 UTC, IgorWolkov reviewed
The solution needed to be discussed in person.

2022-06-29 15:14 UTC, IgorWolkov approved these changes
Let it be.

2022-06-29 15:15 UTC, merged